name: Keycloak.Net Client

variables:
  Version.MajorMinor: 0.1
  Version.Revision: $[counter(variables['Version.MajorMinor'], 0)]

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: test
  displayName: test
  steps:
  - task: PowerShell@2
    displayName: 'Run a multi-line script'  
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)/build/test.ps1        

- job: build
  dependsOn: test
  condition: succeeded()
  displayName: build
  steps:
  - task: PowerShell@2
    displayName: 'Run a multi-line script'  
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)/build/build.ps1
      arguments: BuildVersionNumber=$(Version.Revision)
